title: Train GAN / MNIST (with Adam)

device: &device cuda:1
parallel: false

task:
  object: adversarial_learning

data:
  train:
    name: MNIST
    root: data/
    download: true
    mode: train

model:
  name: GAN
  z_dim: 100
  img_dim: !!python/tuple [1, 28, 28]

hyperparameters:
  optim: Adam
  gen_lr: 0.0002
  disc_lr: 0.0002
  epochs: 200
  batch_size: 64

save:
  name: gan.mnist.adam
  weights_path: saved/weights
  loss_path: saved/loss